export type { AuthInstance, CreateAuthOptions } from './create-auth.js'
export { createAuth } from './create-auth.js'
export type { Hasher } from './hasher.js'
export { pbkdf2Hasher } from './hashers/pbkdf2.js'
export type { SignOptions } from './jwt.js'
export { sign, verify } from './jwt.js'
export { authMiddleware } from './middleware.js'
