// AUTO-GENERATED by `nanoka generate`. DO NOT EDIT BY HAND.
// To regenerate: `npx nanoka generate`
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const users = sqliteTable('users', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  passwordHash: text('passwordHash').notNull(),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})

export const posts = sqliteTable('posts', {
  id: text('id').primaryKey().notNull(),
  userId: text('userId').notNull(),
  title: text('title').notNull(),
  body: text('body'),
  createdAt: integer('createdAt', { mode: 'timestamp_ms' }).notNull(),
})
