import { renderField } from './render-field'
import type { ModelDef } from './types'

const USED_DRIZZLE_IMPORTS = {
  text: false,
  integer: false,
  real: false,
  sqliteTable: false,
}

function detectImports(
  models: readonly ModelDef[],
): Record<keyof typeof USED_DRIZZLE_IMPORTS, boolean> {
  const imports = { ...USED_DRIZZLE_IMPORTS }

  for (const model of models) {
    for (const field of Object.values(model.fields)) {
      const kind = field.kind

      if (kind === 'string' || kind === 'uuid' || kind === 'json') {
        imports.text = true
      } else if (kind === 'number') {
        imports.real = true
      } else if (kind === 'integer' || kind === 'boolean' || kind === 'timestamp') {
        imports.integer = true
      }
    }

    if (Object.values(model.fields).length > 0) {
      imports.sqliteTable = true
    }
  }

  return imports
}

function buildImportStatement(imports: Record<keyof typeof USED_DRIZZLE_IMPORTS, boolean>): string {
  const used: string[] = []

  if (imports.integer) used.push('integer')
  if (imports.real) used.push('real')
  if (imports.sqliteTable) used.push('sqliteTable')
  if (imports.text) used.push('text')

  if (used.length === 0) {
    return "import { sqliteTable } from 'drizzle-orm/sqlite-core'"
  }

  return `import { ${used.join(', ')} } from 'drizzle-orm/sqlite-core'`
}

export function generateDrizzleSchema(models: readonly ModelDef[]): string {
  const imports = detectImports(models)
  const importStatement = buildImportStatement(imports)

  const lines: string[] = [
    '// AUTO-GENERATED by `nanoka generate`. DO NOT EDIT BY HAND.',
    '// To regenerate: `npx nanoka generate`',
    importStatement,
    '',
  ]

  for (const model of models) {
    const fieldLines: string[] = []

    for (const [fieldName, field] of Object.entries(model.fields)) {
      fieldLines.push(renderField(fieldName, field))
    }

    const fieldsStr = fieldLines.length > 0 ? fieldLines.join('\n') : ''
    const tableContent = fieldsStr ? `{\n${fieldsStr}\n}` : '{}'

    lines.push(
      `export const ${model.name} = sqliteTable('${model.name}', ${tableContent})`,
    )
    lines.push('')
  }

  // Remove trailing empty line and add single newline at EOF
  while (lines.length > 0 && lines[lines.length - 1] === '') {
    lines.pop()
  }

  return lines.join('\n') + '\n'
}
